name: hotel_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.13
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 500
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 700
    - family: SF
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 900
